### ISSUE TITLE
Some questions about the implementation of the components and its props

### ISSUE THREAD

**Issue by ChaoYuLeo** [zzuu666/antue#30]
在Ant-design文档中，多数表单组件规定了**value** 、**checked** 、**defaultValue** 、**defaultChecked** 其中之一的 **props**，但是其中的含义在Vue中是否适用值得讨论。

表单类组件的实现，是否应该考虑Vue的特色，加入`v-model`双向数据绑定的功能。以目前组件库中的radio组件为例，并没有为Vue而特殊设计；另外，如果加入`v-model`功能，部分组件的value属性在antd的一些组件(checkbox等)中仅仅作为该选项的标志，这与v-model语法糖依赖于value和组件内部`$emit('input', val)`的做法是相冲突的。

**Comment by sky-admin** [comment]
radio有实现v-model，冲突问题vue官方提供了解决方案：https://cn.vuejs.org/v2/guide/components.html#自定义组件的-v-model  。

**Comment by sky-admin** [comment]
defaultXXX我们商量后认为暂时是不需要的

**Comment by ChaoYuLeo** [comment]
THX
