### ISSUE TITLE
ant-design样式文件不统一

### ISSUE THREAD

**Issue by loocao** [zzuu666/antue#47]
今天fork了个版本,想试着开发下.遇到了个问题:
通过Clone Ant-Design
```
git clone git@github.com:ant-design/ant-design.git --depth=10
```
拉取的ant-design是最新版本的样式文件,很多基础样式变量都不存在!
### 可否先基于统一版本的ant-design样式开发,然后再作升级?
目前ant-design已经发布了3.0.0版本,而我发现antue的`themes/default.less`甚至低于ant-design的`2.x-stable`分支版本,这样开发者就不容易定位到具体使用哪个版本的样式文件,出现我现在遇到的问题.
> 建议先基于`2.x-stable`版本开发,稳定下来之后再逐步升级到新的ant-design样式

**Comment by sky-admin** [comment]
嗯，确实有所疏忽，版本问题我们打算是先以2.x开发一套，放在分支2.x上，再升级3.x，这样2、3都有还是美滋滋，开发文档指南中这一块当时没注意有这个问题。低于2.x-stable版本我们尽快换一下。可能是我们比较拖沓，没赶上antd发稳定版的速度。

**Comment by zzuu666** [comment]
目前 antue 所用的样式版本确实落后于 antd，下周（12.17之前）会统一将目前组件样式升级到 `2.x-stable` 版本，并在开发规范里面同步所基于的 antd 的版本。

后续完成组件后，会新开分支升级3.0样式。
