### ISSUE TITLE
inputnumber是不是没有移植？

### ISSUE THREAD

**Issue by ibegyourpardon** [zzuu666/antue#54]
在开发的时候发现只有 input 组件，没有 inputnumber

**Comment by ibegyourpardon** [comment]
……在 input 里看到了type 参数，是我自己没看清楚……

**Comment by sky-admin** [comment]
确实是还没移植，type=number靠的是原生的input框支持。

**Comment by ibegyourpardon** [comment]
是的，不仅 typenumber 是靠原生的支持，而且对原生的限制数字范围的 min 和 max 也没有支持。考虑到重写一份太过复杂，业务赶不上，决定先靠 JS 处理掉了… 还是希望以后能增加上单独的 inputnumber ，以及对 input 的更多的支持。
